// Curated starter recipes shown in the Community library for every user,
// regardless of whether anyone has shared a recipe yet. These aren't stored
// in Firestore — they ship with the app. "Save to my recipes" copies one into
// the signed-in user's own private collection just like a shared recipe would.

export const STARTER_RECIPES = [
  {
    id: 'starter-breakfast-oat-pot',
    isStarter: true,
    authorName: 'Starter Recipes',
    title: 'Blueberry & Chia Breakfast Pot',
    category: 'breakfast',
    calories: 310,
    servings: 1,
    ingredients: [
      '1/2 cup rolled oats (gluten-free if needed)',
      '1 cup lactose-free milk',
      '1 tbsp chia seeds',
      '1/2 cup blueberries',
      '1 tsp maple syrup',
      'Pinch of cinnamon',
    ].join('\n'),
    instructions: [
      'Combine oats, lactose-free milk, and chia seeds in a jar.',
      'Stir well, cover, and refrigerate overnight.',
      'In the morning, top with blueberries, maple syrup, and a pinch of cinnamon.',
    ].join('\n'),
    notes: 'A great make-ahead breakfast — prep several jars at once for the week.',
    image: '',
  },
  {
    id: 'starter-lunch-chicken-quinoa',
    isStarter: true,
    authorName: 'Starter Recipes',
    title: 'Grilled Chicken & Quinoa Salad',
    category: 'lunch',
    calories: 420,
    servings: 2,
    ingredients: [
      '1 cup cooked quinoa',
      '2 grilled chicken breasts, sliced',
      '1 cup cherry tomatoes, halved',
      '1 cup baby spinach',
      '1/4 cup crumbled feta (lactose-free if needed)',
      '2 tbsp garlic-infused olive oil',
      '1 tbsp lemon juice',
      'Salt and pepper to taste',
    ].join('\n'),
    instructions: [
      'Whisk garlic-infused oil, lemon juice, salt, and pepper for the dressing.',
      'Toss quinoa, spinach, and tomatoes with the dressing.',
      'Top with sliced chicken and crumbled feta before serving.',
    ].join('\n'),
    notes: 'Garlic-infused oil adds flavor without the raw bite — swap in any protein you like.',
    image: '',
  },
  {
    id: 'starter-dinner-salmon-potatoes',
    isStarter: true,
    authorName: 'Starter Recipes',
    title: 'Lemon Herb Baked Salmon with Roasted Potatoes',
    category: 'dinner',
    calories: 520,
    servings: 2,
    ingredients: [
      '2 salmon fillets',
      '2 cups baby potatoes, halved',
      '1 tbsp olive oil',
      '1 lemon, sliced',
      '1 tsp dried dill',
      '1 cup green beans, trimmed',
      'Salt and pepper to taste',
    ].join('\n'),
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Toss potatoes with olive oil, salt, and pepper; roast 20 minutes.',
      'Add salmon and green beans to the tray, top salmon with lemon slices and dill.',
      'Roast another 12-15 minutes until salmon flakes easily.',
    ].join('\n'),
    notes: 'A simple one-tray dinner — swap in any firm white fish if you don’t have salmon.',
    image: '',
  },
  {
    id: 'starter-dinner-beef-stirfry',
    isStarter: true,
    authorName: 'Starter Recipes',
    title: 'Beef & Green Bean Stir-Fry with Rice Noodles',
    category: 'dinner',
    calories: 480,
    servings: 2,
    ingredients: [
      '250g beef strips',
      '2 cups green beans, trimmed',
      '1 red bell pepper, sliced',
      '150g rice noodles',
      '2 tbsp garlic-infused oil',
      '2 tbsp gluten-free soy sauce',
      '1 tsp fresh ginger, minced',
      '1 tbsp sesame seeds',
    ].join('\n'),
    instructions: [
      'Cook rice noodles according to package instructions; set aside.',
      'Stir-fry beef in garlic-infused oil until browned, then remove from pan.',
      'Stir-fry green beans, bell pepper, and ginger for 3-4 minutes.',
      'Return beef to the pan, add soy sauce and noodles, and toss to combine.',
      'Top with sesame seeds before serving.',
    ].join('\n'),
    notes: 'Fresh ginger and garlic-infused oil keep this dish flavorful and easy on digestion.',
    image: '',
  },
  {
    id: 'starter-dessert-yogurt-bark',
    isStarter: true,
    authorName: 'Starter Recipes',
    title: 'Strawberry Lactose-Free Yogurt Bark',
    category: 'dessert',
    calories: 180,
    servings: 4,
    ingredients: [
      '2 cups lactose-free plain yogurt',
      '1 tbsp maple syrup',
      '1/2 cup strawberries, sliced',
      '2 tbsp chopped walnuts',
      '1 tbsp shredded coconut',
    ].join('\n'),
    instructions: [
      'Line a baking tray with parchment paper.',
      'Mix yogurt with maple syrup and spread evenly on the tray.',
      'Scatter strawberries, walnuts, and coconut over the top.',
      'Freeze for at least 3 hours, then break into pieces to serve.',
    ].join('\n'),
    notes: 'A frozen treat that stays within a 1/2 cup strawberry and small walnut portion per serving.',
    image: '',
  },
]
